const sectors = [
  "Banking",
  "IT",
  "Energy",
  "Auto",
  "Pharma",
  "FMCG",
  "Metals",
  "Finance",
  "Infra",
  "Consumer",
];

const rawStocks = [
  ["RELIANCE", "Reliance Industries"], ["TCS", "Tata Consultancy Services"], ["HDFCBANK", "HDFC Bank"], ["ICICIBANK", "ICICI Bank"],
  ["INFY", "Infosys"], ["SBIN", "State Bank of India"], ["BHARTIARTL", "Bharti Airtel"], ["ITC", "ITC"], ["LT", "Larsen & Toubro"],
  ["AXISBANK", "Axis Bank"], ["KOTAKBANK", "Kotak Mahindra Bank"], ["HINDUNILVR", "Hindustan Unilever"], ["BAJFINANCE", "Bajaj Finance"],
  ["ASIANPAINT", "Asian Paints"], ["MARUTI", "Maruti Suzuki"], ["SUNPHARMA", "Sun Pharmaceutical"], ["TITAN", "Titan Company"],
  ["WIPRO", "Wipro"], ["TATAMOTORS", "Tata Motors"], ["ADANIENT", "Adani Enterprises"], ["HCLTECH", "HCL Technologies"],
  ["TECHM", "Tech Mahindra"], ["ULTRACEMCO", "UltraTech Cement"], ["NESTLEIND", "Nestle India"], ["POWERGRID", "Power Grid"],
  ["ONGC", "Oil & Natural Gas Corp"], ["NTPC", "NTPC"], ["COALINDIA", "Coal India"], ["JSWSTEEL", "JSW Steel"], ["TATASTEEL", "Tata Steel"],
  ["CIPLA", "Cipla"], ["DRREDDY", "Dr Reddy's Labs"], ["DIVISLAB", "Divi's Laboratories"], ["EICHERMOT", "Eicher Motors"],
  ["HEROMOTOCO", "Hero MotoCorp"], ["BAJAJFINSV", "Bajaj Finserv"], ["BAJAJ-AUTO", "Bajaj Auto"], ["M&M", "Mahindra & Mahindra"],
  ["GRASIM", "Grasim Industries"], ["HDFCLIFE", "HDFC Life"], ["SBILIFE", "SBI Life Insurance"], ["APOLLOHOSP", "Apollo Hospitals"],
  ["BRITANNIA", "Britannia Industries"], ["ADANIPORTS", "Adani Ports"], ["BPCL", "Bharat Petroleum"], ["IOC", "Indian Oil"],
  ["HINDALCO", "Hindalco"], ["INDUSINDBK", "IndusInd Bank"], ["TATACONSUM", "Tata Consumer"], ["SHRIRAMFIN", "Shriram Finance"],
  ["TRENT", "Trent"], ["BEL", "Bharat Electronics"], ["JIOFIN", "Jio Financial Services"], ["ADANIGREEN", "Adani Green Energy"],
  ["ADANIPOWER", "Adani Power"], ["ADANITRANS", "Adani Energy Solutions"], ["AMBUJACEM", "Ambuja Cements"], ["ACC", "ACC"],
  ["DMART", "Avenue Supermarts"], ["GODREJCP", "Godrej Consumer"], ["DABUR", "Dabur India"], ["COLPAL", "Colgate Palmolive"],
  ["MARICO", "Marico"], ["PIDILITIND", "Pidilite Industries"], ["BERGEPAINT", "Berger Paints"], ["HAVELLS", "Havells India"],
  ["VOLTAS", "Voltas"], ["BLUESTARCO", "Blue Star"], ["CROMPTON", "Crompton Greaves Consumer"], ["POLYCAB", "Polycab India"],
  ["ABB", "ABB India"], ["SIEMENS", "Siemens"], ["BHEL", "Bharat Heavy Electricals"], ["HAL", "Hindustan Aeronautics"],
  ["BOSCHLTD", "Bosch"], ["CUMMINSIND", "Cummins India"], ["ASHOKLEY", "Ashok Leyland"], ["TVSMOTOR", "TVS Motor"],
  ["ESCORTS", "Escorts Kubota"], ["MOTHERSON", "Samvardhana Motherson"], ["BALKRISIND", "Balkrishna Industries"], ["MRF", "MRF"],
  ["APOLLOTYRE", "Apollo Tyres"], ["CEAT", "CEAT"], ["EXIDEIND", "Exide Industries"], ["AMARAJABAT", "Amara Raja Energy"],
  ["BANKBARODA", "Bank of Baroda"], ["PNB", "Punjab National Bank"], ["CANBK", "Canara Bank"], ["UNIONBANK", "Union Bank of India"],
  ["IDFCFIRSTB", "IDFC First Bank"], ["FEDERALBNK", "Federal Bank"], ["BANDHANBNK", "Bandhan Bank"], ["AUBANK", "AU Small Finance Bank"],
  ["RBLBANK", "RBL Bank"], ["YESBANK", "Yes Bank"], ["CHOLAFIN", "Cholamandalam Investment"], ["MUTHOOTFIN", "Muthoot Finance"],
  ["MANAPPURAM", "Manappuram Finance"], ["LICHSGFIN", "LIC Housing Finance"], ["PFC", "Power Finance Corp"], ["RECLTD", "REC"],
  ["IRFC", "Indian Railway Finance Corp"], ["HUDCO", "HUDCO"], ["SBICARD", "SBI Cards"], ["ICICIPRULI", "ICICI Prudential Life"],
  ["ICICIGI", "ICICI Lombard"], ["BAJAJHLDNG", "Bajaj Holdings"], ["HDFCAMC", "HDFC AMC"], ["NAM-INDIA", "Nippon Life AMC"],
  ["CDSL", "Central Depository Services"], ["BSE", "BSE"], ["MCX", "Multi Commodity Exchange"], ["ANGELONE", "Angel One"],
  ["IEX", "Indian Energy Exchange"], ["LTIM", "LTIMindtree"], ["PERSISTENT", "Persistent Systems"], ["MPHASIS", "Mphasis"],
  ["COFORGE", "Coforge"], ["OFSS", "Oracle Financial Services"], ["TATAELXSI", "Tata Elxsi"], ["LTTS", "L&T Technology Services"],
  ["KPITTECH", "KPIT Technologies"], ["CYIENT", "Cyient"], ["SONATSOFTW", "Sonata Software"], ["ZENSARTECH", "Zensar Technologies"],
  ["AFFLE", "Affle India"], ["NAUKRI", "Info Edge"], ["NYKAA", "FSN E-Commerce"], ["PAYTM", "One 97 Communications"],
  ["ZOMATO", "Zomato"], ["POLICYBZR", "PB Fintech"], ["MAPMYINDIA", "CE Info Systems"], ["TANLA", "Tanla Platforms"],
  ["LUPIN", "Lupin"], ["AUROPHARMA", "Aurobindo Pharma"], ["ZYDUSLIFE", "Zydus Lifesciences"], ["TORNTPHARM", "Torrent Pharma"],
  ["ALKEM", "Alkem Laboratories"], ["GLAND", "Gland Pharma"], ["BIOCON", "Biocon"], ["LAURUSLABS", "Laurus Labs"],
  ["IPCALAB", "IPCA Laboratories"], ["GLENMARK", "Glenmark Pharma"], ["NATCOPHARM", "Natco Pharma"], ["AJANTPHARM", "Ajanta Pharma"],
  ["ABBOTINDIA", "Abbott India"], ["PFIZER", "Pfizer"], ["SANOFI", "Sanofi India"], ["MAXHEALTH", "Max Healthcare"],
  ["FORTIS", "Fortis Healthcare"], ["LALPATHLAB", "Dr Lal PathLabs"], ["METROPOLIS", "Metropolis Healthcare"], ["NH", "Narayana Hrudayalaya"],
  ["HINDPETRO", "Hindustan Petroleum"], ["GAIL", "GAIL India"], ["PETRONET", "Petronet LNG"], ["OIL", "Oil India"],
  ["IGL", "Indraprastha Gas"], ["MGL", "Mahanagar Gas"], ["GUJGASLTD", "Gujarat Gas"], ["ATGL", "Adani Total Gas"],
  ["TATAPOWER", "Tata Power"], ["JSWENERGY", "JSW Energy"], ["NHPC", "NHPC"], ["SJVN", "SJVN"], ["TORNTPOWER", "Torrent Power"],
  ["CESC", "CESC"], ["THERMAX", "Thermax"], ["KEI", "KEI Industries"], ["FINCABLES", "Finolex Cables"], ["VGUARD", "V-Guard"],
  ["SAIL", "Steel Authority of India"], ["JINDALSTEL", "Jindal Steel"], ["NMDC", "NMDC"], ["VEDL", "Vedanta"], ["NATIONALUM", "National Aluminium"],
  ["HINDZINC", "Hindustan Zinc"], ["APLAPOLLO", "APL Apollo Tubes"], ["RATNAMANI", "Ratnamani Metals"], ["WELCORP", "Welspun Corp"],
  ["JSL", "Jindal Stainless"], ["HINDCOPPER", "Hindustan Copper"], ["CENTURYPLY", "Century Plyboards"], ["GREENPLY", "Greenply Industries"],
  ["DLF", "DLF"], ["GODREJPROP", "Godrej Properties"], ["OBEROIRLTY", "Oberoi Realty"], ["PRESTIGE", "Prestige Estates"],
  ["PHOENIXLTD", "Phoenix Mills"], ["BRIGADE", "Brigade Enterprises"], ["SOBHA", "Sobha"], ["LODHA", "Macrotech Developers"],
  ["IRCTC", "IRCTC"], ["INDIGO", "InterGlobe Aviation"], ["CONCOR", "Container Corp"], ["DELHIVERY", "Delhivery"],
  ["BLUEDART", "Blue Dart Express"], ["VRLLOG", "VRL Logistics"], ["MAHLOG", "Mahindra Logistics"], ["TCI", "Transport Corp of India"],
  ["TATACHEM", "Tata Chemicals"], ["DEEPAKNTR", "Deepak Nitrite"], ["AARTIIND", "Aarti Industries"], ["SRF", "SRF"],
  ["PIIND", "PI Industries"], ["UPL", "UPL"], ["COROMANDEL", "Coromandel International"], ["GNFC", "GNFC"], ["GSFC", "GSFC"],
  ["NAVINFLUOR", "Navin Fluorine"], ["FLUOROCHEM", "Gujarat Fluorochemicals"], ["ALKYLAMINE", "Alkyl Amines"], ["TATVA", "Tatva Chintan"],
  ["VINATIORGA", "Vinati Organics"], ["ATUL", "Atul"], ["BASF", "BASF India"], ["KANSAINER", "Kansai Nerolac"],
  ["INDHOTEL", "Indian Hotels"], ["EIHOTEL", "EIH"], ["CHALET", "Chalet Hotels"], ["LEMONTREE", "Lemon Tree Hotels"],
  ["JUBLFOOD", "Jubilant FoodWorks"], ["DEVYANI", "Devyani International"], ["SAPPHIRE", "Sapphire Foods"], ["WESTLIFE", "Westlife Foodworld"],
  ["VBL", "Varun Beverages"], ["UBL", "United Breweries"], ["UNITDSPR", "United Spirits"], ["RADICO", "Radico Khaitan"],
  ["MCDOWELL-N", "United Spirits"], ["PAGEIND", "Page Industries"], ["KPRMILL", "KPR Mill"], ["RAYMOND", "Raymond"],
  ["ABFRL", "Aditya Birla Fashion"], ["SHOPERSTOP", "Shoppers Stop"], ["VMART", "V-Mart Retail"], ["METROBRAND", "Metro Brands"],
  ["RELAXO", "Relaxo Footwears"], ["BATAINDIA", "Bata India"], ["CAMPUS", "Campus Activewear"], ["TRENT", "Trent"],
  ["JUBLINGREA", "Jubilant Ingrevia"], ["ASTRAL", "Astral"], ["SUPREMEIND", "Supreme Industries"], ["PRINCEPIPE", "Prince Pipes"],
  ["FINPIPE", "Finolex Industries"], ["KAJARIACER", "Kajaria Ceramics"], ["CERA", "Cera Sanitaryware"], ["HSIL", "HSIL"],
  ["TATACOMM", "Tata Communications"], ["ITI", "ITI"], ["HFCL", "HFCL"], ["TEJASNET", "Tejas Networks"],
  ["IDEA", "Vodafone Idea"], ["ROUTE", "Route Mobile"], ["RAILTEL", "RailTel"], ["IRCON", "Ircon International"],
  ["RVNL", "Rail Vikas Nigam"], ["NBCC", "NBCC"], ["NCC", "NCC"], ["PNCINFRA", "PNC Infratech"], ["KNRCON", "KNR Constructions"],
  ["L&TFH", "L&T Finance"], ["IDBI", "IDBI Bank"], ["CENTRALBK", "Central Bank of India"], ["UCOBANK", "UCO Bank"],
  ["IOB", "Indian Overseas Bank"], ["MAZDOCK", "Mazagon Dock"], ["COCHINSHIP", "Cochin Shipyard"], ["GRSE", "Garden Reach Shipbuilders"],
  ["BEML", "BEML"], ["BDL", "Bharat Dynamics"], ["MIDHANI", "Mishra Dhatu Nigam"], ["IDEAFORGE", "ideaForge Technology"],
  ["DIXON", "Dixon Technologies"], ["AMBER", "Amber Enterprises"], ["KAYNES", "Kaynes Technology"], ["SYRMA", "Syrma SGS"],
  ["PGEL", "PG Electroplast"], ["AIAENG", "AIA Engineering"], ["SKFINDIA", "SKF India"], ["TIMKEN", "Timken India"],
  ["SCHAEFFLER", "Schaeffler India"], ["CARBORUNIV", "Carborundum Universal"], ["ELGIEQUIP", "Elgi Equipments"], ["GRINDWELL", "Grindwell Norton"],
  ["JKCEMENT", "JK Cement"], ["DALBHARAT", "Dalmia Bharat"], ["RAMCOCEM", "Ramco Cements"], ["SHREECEM", "Shree Cement"],
  ["HEIDELBERG", "HeidelbergCement India"], ["ORIENTCEM", "Orient Cement"], ["NUVOCO", "Nuvoco Vistas"], ["JKLAKSHMI", "JK Lakshmi Cement"],
];

export const NSE_STOCKS = rawStocks.map(([symbol, name], index) => ({
  id: `${symbol}-${index}`,
  symbol,
  name,
  exchange: "NSE",
  sector: sectors[index % sectors.length],
  allowed: index < 18,
}));
